# Generated by Django 2.1.2 on 2018-10-10 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registDate', models.DateField(auto_now=True)),
                ('status', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('minRentDay', models.IntegerField()),
                ('maxRentDay', models.IntegerField()),
                ('picture', models.TextField()),
                ('info', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
