# Generated by Django 2.1.2 on 2018-10-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postCode', models.IntegerField()),
                ('address', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=11)),
                ('grade', models.IntegerField()),
                ('accountInfo', models.CharField(max_length=128)),
                ('userInfo', models.CharField(max_length=128)),
            ],
        ),
    ]
