# Generated by Django 2.1.2 on 2018-10-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accountInfo',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='postCode',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='userInfo',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
